export default {
  lenguas: [
    "Nahual",
    "Tu´un Savi (Mixteco)",
    "Meephaa (Tlapaneco)",
    "Amuzgo",
    "Ninguno",
  ],
  derechohabiencias: [
    "INSABI",
    "IMSS",
    "ISSSTE",
    "SEDENA",
    "PEMEX",
    "MARINA",
    "Otro",
  ],
  complicaciones: [
    "Hemorragia",
    "Retención de placenta",
    "Placenta previa",
    "Diabetes gestacional",
    "Preeclampsia",
    "Eclampsia",
    "Covid + embarazo",
    "Otra",
  ],
  metodospf: [
    "OTB",
    "DIU",
    "IMPLANTE",
    "INY. BIMENSUAL",
    "INY. MENSUAL",
    "H.O. MENSUAL",
    "PARCHE",
    "OTRO",
    "NINGUNO",
  ],
  consultasEmbarazo: [
    "SIN CONTROL",
    "1-3 CONSULTAS",
    "4 A 6 CONSULTAS",
    "7 A 9 CONSULTAS",
    "MAS DE 10 CONSULTAS",
  ],
  grupoRH: ["A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-"],
  ego: [
    "Prot. Trazas",
    "Prot. >300 MG/L",
    "LEUCOCITOS > 5",
    "NITRATOS +",
    "NEGATIVO",
  ],
  BiometriaHematica: ["HB >= 12", "HB >=9 Y <12", "HB < 9", "Ninguno"],
  VDRL: ["REACTIVO", "NO REACTIVO", "NO SE REALIZÓ"],
  estadoGlucosa: ["Ayuno", "Posprandial 1 Hora", "Posprandial 2 horas", "-"],
  resultadoGlucosa: [
    "60 y menor a 110",
    ">=110 y menor o igual a 126",
    "126 y menor a 160",
  ],
  caracteristicasFetls:["Unico vivo","Unico obito","Molar","Monocorial",
  "Bicorionicos","Gmelar 1 obitado"],
malformaciones:["Espina bifida","Gastrosquisis","Meningocele","Mielomeningocele","Anencefalia","Otras","Ninguna"],
liquidoAmiotico:["Normal","Oligohidramnios","Polihidramnios","Anhidramnios"],
placenta:["Normal Sin alteraciones","Previa","Acretismo placentario","Calcificada","Otra"]
};
